core/urls.py
from django.contrib import admin
from django.urls import path
from core.views import BooksListView, BooksDetailView, BooksAddView, BooksUpdateView
from core import views

app_name = "core"

urlpatterns = [
    path('index', views.index, name="index"),
    path('books', BooksListView.as_view(), name='books'),
    path('book/<int:pk>', BooksDetailView.as_view(), name="book"),
    path('book/add', BooksAddView.as_view(), name="create"),
    path('book/update/<int:pk>', BooksUpdateView.as_view(), name="update")
]

it_code_lab_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('core.urls', namespace="core"))
]

core/models.py
from django.db import models


# Create your models here.
class Library(models.Model):
    address = models.TextField(help_text="Адрес")
    # books = models.ManyToManyField(Book)


class Book(models.Model):
    title = models.CharField(max_length=255, help_text="Название")
    genre = models.CharField(max_length=255, help_text="Жанр")
    author = models.CharField(max_length=255, help_text="Автор")
    pages = models.IntegerField()
    # library = models.ForeignKey(to=Library, on_delete=models.PROTECT, null=True)


class Subscriber(models.Model):
    name = models.CharField(max_length=255)
    library = models.ManyToManyField(Library)


if __name__ == '__main__':
    Subscriber.objects.acount()

core/forms.py
from django.forms import forms

from core.models import Book
from django.forms import ModelForm


class BookCreateForm(ModelForm):
    class Meta:
        model = Book
        fields = ("title", "author", "genre", "pages")

# class BookUpdateForm(ModelForm):

core/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from core.forms import BookCreateForm
from core.models import Book
from django.template import loader


# Create your views here.


class BooksListView(ListView):
    model = Book
    template_name = "books.html"
    paginate_by = 100  # if pagination is desired

    def get_queryset(self):
        filter_val = self.request.GET.get('filter', '')
        new_context = Book.objects.filter(
            title__contains=filter_val,
        )
        return new_context

    def get_context_data(self, **kwargs):
        context = super(BooksListView, self).get_context_data(**kwargs)
        context['filter'] = self.request.GET.get('filter', '')
        return context


class BooksDetailView(DetailView):
    model = Book
    template_name = "book.html"


class BooksAddView(CreateView):
    model = Book
    template_name = "book_add.html"

    def get(self, request, *args, **kwargs):
        context = {'form': BookCreateForm()}
        return render(request, 'book_add.html', context)

    def post(self, request, *args, **kwargs):
        form = BookCreateForm(request.POST)
        if form.is_valid():
            book = form.save()
            book.save()
            return HttpResponseRedirect(reverse_lazy('core:books'))
        return render(request, 'book_add.html', {'form': form})


class BooksUpdateView(UpdateView):
    model = Book
    template_name = "book_add.html"
    fields = ("title", "author", "genre", "pages")
    # form_class = BookCreateForm



def index(request):
    count = Book.objects.count()
    template = loader.get_template("index.html")
    return HttpResponse(template.render({"count": count}, request))

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <title>Книги</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
    <!--    <a class="navbar-brand" href="#"></a>-->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/books">Список книг</a>
            </li>
              <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/book/add">Добавить книгу</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}{% endblock %}
{#<div class="container-lg">#}
{#    <table class="table">#}
{#      <thead>#}
{#        <tr>#}
{#          <th scope="col">#</th>#}
{#          <th scope="col">ФИО</th>#}
{#          <th scope="col">Должность</th>#}
{#          <th scope="col">Телефон</th>#}
{#        </tr>#}
{#      </thead>#}
{#      <tbody>#}
{#        <tr>#}
{#          <th scope="row">1</th>#}
{#          <td>Юдин Феликс Геласьевич</td>#}
{#          <td>Менеджер по продажам</td>#}
{#          <td>+7 987-654-32-10</td>#}
{#        </tr>#}
{#        <tr>#}
{#          <th scope="row">2</th>#}
{#          <td>Красильников Семен Альвианович</td>#}
{#          <td>Юрист</td>#}
{#          <td>+7 987-654-32-10</td>#}
{#        </tr>#}
{#        <tr>#}
{#            <th scope="row">3</th>#}
{#            <td>Бурова Силика Витальевна</td>#}
{#            <td>Делопроизводитель</td>#}
{#            <td>+7 987-654-32-10</td>#}
{#        </tr>#}
{#      </tbody>#}
{#    </table>#}
{#</div>#}
</body>
</html>

templates/book.html
{% extends "./base.html" %}


{% block content %}
    <p>
        {{ book.title }} - {{ book.author }}
    </p>
    <p>
        Жанр: {{ book.genre }}
    </p>
    <p>
        Кол-во страниц: {{ book.pages }}
    </p>

{% endblock %}

templates/book_add.html
<form action="{% url 'core:create' %}" method="POST">

{% csrf_token %}

<table>
    {{ form.as_table }}
</table>
<button type="submit">SUBMIT</button>
</form>

templates/books.html
{% extends "./base.html" %}


{% block content %}
    <form method="get" action="{% url 'core:books' %}">
        <p>Filter: <input type="text" value="{{filter}}" name="filter"/></p>
        <p><input type="submit"/></p>
    </form>
    {% for book in object_list %}
        <li>{{ book.title }} - {{ book.author }} (<a href="book/{{ book.id }}">Перейти</a>)</li>
    {% empty %}
    <li>No books yet.</li>
{% endfor %}
{% endblock %}

templates/index.html
{% extends "./base.html" %}


{% block content %}
    Кол-во книг загружено: {{ count }}
{% endblock %}